version: "3"
services:
  information-gathering-managiment:
    build:
      context: .
      target: prod
    ports:
      - 8000:8000
      - 8080:8080
    command: pipenv run start
    tty: true

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/database/.env
    ports:
      - 5432:5432
